export const USER_REQUEST = "USER_REQUEST"
export const USER_SUCCESS = "USER_SUCCESS"
export const USER_FAILURE = "USER_FAILURE"

export const GET_USER_REQUEST = "GET_USER_REQUEST"
export const GET_USER_SUCCESS = "GET_USER_SUCCESS"
export const GET_USER_FAILURE = "GET_USER_FAILURE"

export const GET_ID_USER_REQUEST = "GET_ID_USER_REQUEST"
export const GET_ID_USER_SUCCESS = "GET_ID_USER_SUCCESS"
export const GET_ID_USER_FAILURE = "GET_ID_USER_FAILURE"

export const UPDATE_REQUEST = "UPDATE_REQUEST"
export const UPDATE_SUCCESS = "UPDATE_SUCCESS"
export const UPDATE_FAILURE = "UPDATE_FAILURE"

export const DELETE_REQUEST = "DELETE_REQUEST"
export const DELETE_SUCCESS = "DELETE_SUCCESS"
export const DELETE_FAILURE = "DELETE_FAILURE"